### ISSUE TITLE
No translation file found for domain: 'bot'

### ISSUE THREAD

**Issue by beucismis** [CircuitsBots/discord-i18n#1]
I just ran run.py file.

Error:
```
 $ python3 run.py 
Traceback (most recent call last):
  File "/home/adil/Clones/discord-i18n/run.py", line 5, in <module>
    from app.bot import Bot
  File "/home/adil/Clones/discord-i18n/app/bot.py", line 3, in <module>
    from app.i18n import current_locale, lazy_translate as _l
  File "/home/adil/Clones/discord-i18n/app/i18n.py", line 18, in <module>
    gettext_translations = {
  File "/home/adil/Clones/discord-i18n/app/i18n.py", line 19, in <dictcomp>
    locale: gettext.translation(
  File "/usr/lib/python3.9/gettext.py", line 607, in translation
    raise FileNotFoundError(ENOENT,
FileNotFoundError: [Errno 2] No translation file found for domain: 'bot'
```

**Comment by circuitsacul** [comment]
Did you try to launch the bot, or did this error occur as soon as you ran run.py?

**Comment by beucismis** [comment]
Soon as you ran run.py

**Comment by circuitsacul** [comment]
I think it's fixed now, could you clone and retry?

**Comment by beucismis** [comment]
Good job. Thanks.
